CREATE TABLE PET(PET_ID INT,
PET_NAME VARCHAR(15),
PET_TYPE VARCHAR(15) ,
PET_AGE INT,
PET_OWNER VARCHAR(15),
CONSTRAINT PET_PRIMARY_KEY PRIMARY KEY (PET_ID) ) ;





CREATE TABLE PET_VISIT(PET_ID INT,
VISIT_DATE VARCHAR(20),
PROC_ID INT,
CONSTRAINT PET_VISIT_PRIMARY_KEY PRIMARY KEY (PROC_ID),
CONSTRAINT PET_VISIT_FOREIGN_KEY FOREIGN KEY (PET_ID) REFERENCES PET(PET_ID));



CREATE TABLE PROCS(PROCE VARCHAR(30),
PROC_ID INT,
CONSTRAINT PROCEDURE_FOREIGN_KEY FOREIGN KEY (PROC_ID) REFERENCES PET_VISIT(PROC_ID) ) ;

